# This is a basic workflow to help you get started with Actions

name: FTP Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    #branches: [ master ]
  pull_request:
    #branches: [ master ]
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.techiskey.net/
        ftp-username: github@hkhousinganalysis.techiskey.net
        ftp-password: ${{ secrets.FTP_PASSWORD }}
